spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_connection_url}
    username: ${db_connection_username}
    password: ${db_connection_password}

  profiles:
    active: dev

app-properties:
  client-route: http://localhost:4200
  api-version: /api/v1

token:
  issuer: "Auction Application"
  expiration:
    regular: 1
    persistent: 7
  temporal-unit: DAYS

rsa:
  public-key: 'classpath:cert/key.pub'
  private-key: 'classpath:cert/key.priv'