spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_connection_url}
    username: ${db_connection_username}
    password: ${db_connection_password}

  profiles:
    active: dev