spring:
  datasource:
    driver-class-name: ${db_connection_driver}
    url: ${db_connection_url}
    username: ${db_connection_username}
    password: ${db_connection_password}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.data: DEBUG