CREATE TABLE items
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(50)                              NOT NULL,
    description   VARCHAR(700)                             NOT NULL,
    initial_price DECIMAL(10, 2)                           NOT NULL,
    start_date    date                                     NOT NULL,
    end_date      date                                     NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE items_images
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                             NOT NULL,
    image_url VARCHAR(1000)                            NOT NULL,
    item_id   INTEGER                                  NOT NULL,
    CONSTRAINT pk_items_images PRIMARY KEY (id)
);

ALTER TABLE items_images
    ADD CONSTRAINT FK_ITEMS_IMAGES_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);
