CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER                                   NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)                              NOT NULL,
    type           VARCHAR(20)                               NOT NULL,
    script         VARCHAR(1000)                             NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)                              NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER                                   NOT NULL,
    success        BOOLEAN                                   NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

CREATE TABLE items
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(50)                              NOT NULL,
    description   VARCHAR(700)                             NOT NULL,
    initial_price numeric(10, 2)                           NOT NULL,
    start_date    date                                     NOT NULL,
    end_date      date                                     NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE items_images
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                             NOT NULL,
    image_url VARCHAR(1000)                            NOT NULL,
    item_id   INTEGER                                  NOT NULL,
    CONSTRAINT pk_items_images PRIMARY KEY (id)
);

ALTER TABLE items_images
    ADD CONSTRAINT fk_items_images_on_item FOREIGN KEY (item_id) REFERENCES items (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (1, 'Headphones', 'Placeholder', 29.99, '2023-10-19', '2023-10-30');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (2, 'Shoes', 'Placeholder', 49.99, '2023-10-21', '2023-10-23');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (3, 'Watch', 'Placeholder', 299.99, '2023-10-25', '2023-10-31');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (4, 'Bag', 'Placeholder', 480.00, '2023-10-22', '2023-11-01');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (5, 'Camera', 'Placeholder', 320.00, '2023-10-16', '2023-11-14');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (6, 'White Shoes', 'Placeholder', 120.00, '2023-10-27', '2023-10-28');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (7, 'Body Spray', 'Placeholder', 72.00, '2023-10-22', '2023-10-25');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (8, 'Coco', 'Placeholder', 147.99, '2023-10-29', '2023-10-31');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (9, 'Fragrance', 'Placeholder', 99.99, '2023-11-01', '2023-11-09');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (10, 'Sunglasses', 'Placeholder', 25.00, '2023-10-29', '2023-10-30');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (11, 'Coin', 'Placeholder', 41.00, '2023-10-31', '2023-11-03');
INSERT INTO public.items (id, name, description, initial_price, start_date, end_date) VALUES (12, 'Phone Mask', 'Placeholder', 20.00, '2023-10-23', '2023-10-26');

INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (1, 'Headphones', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cHJvZHVjdHN8ZW58MHx8MHx8fDA%3D', 1);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (2, 'Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJvZHVjdHN8ZW58MHx8MHx8fDA%3D', 2);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (3, 'Watch', 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fHByb2R1Y3RzfGVufDB8fDB8fHww', 3);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (4, 'Bag', 'https://images.unsplash.com/photo-1611254666354-d75bfe3cadbc?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NzB8fHByb2R1Y3RzfGVufDB8fDB8fHww', 4);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (5, 'Camera', 'https://images.unsplash.com/photo-1587467063136-db173523594d?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODd8fHByb2R1Y3RzfGVufDB8fDB8fHww', 5);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (6, 'White Shoes', 'https://images.unsplash.com/flagged/photo-1556637640-2c80d3201be8?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTA0fHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 6);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (7, 'Body Spray', 'https://images.unsplash.com/photo-1627384113944-4822313913c6?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTMxfHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 7);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (8, 'Body Spray', 'https://images.unsplash.com/photo-1532413992378-f169ac26fff0?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTI4fHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 7);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (9, 'Coco', 'https://images.unsplash.com/photo-1592842232655-e5d345cbc2d0?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTQyfHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 8);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (10, 'Fragrance', 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQyfHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 9);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (11, 'Sunglasses', 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjc5fHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 10);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (12, 'Coin', 'https://images.unsplash.com/photo-1617004890831-c99c16006144?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjc2fHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 11);
INSERT INTO public.items_images (id, name, image_url, item_id) VALUES (13, 'Phone Mask', 'https://images.unsplash.com/photo-1592921249123-2dfd435f8690?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDEyfHxwcm9kdWN0c3xlbnwwfHwwfHx8MA%3D%3D', 12);