INSERT INTO public.category (id, name) VALUES (1, 'Fashion');
INSERT INTO public.category (id, name) VALUES (2, 'Accessories');
INSERT INTO public.category (id, name) VALUES (3, 'Jewelry');
INSERT INTO public.category (id, name) VALUES (4, 'Shoes');
INSERT INTO public.category (id, name) VALUES (5, 'Sportswear');
INSERT INTO public.category (id, name) VALUES (6, 'Home');
INSERT INTO public.category (id, name) VALUES (7, 'Electronics');
INSERT INTO public.category (id, name) VALUES (8, 'Mobile');
INSERT INTO public.category (id, name) VALUES (9, 'Computer');
